# Generated by Django 3.2.3 on 2021-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('parent', models.ManyToManyField(to='api_server.FrozenResource')),
            ],
        ),
    ]
