# Generated by Django 3.2.3 on 2021-06-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frozenresource',
            name='parent',
        ),
    ]
