dist: xenial

sudo: true

services:
  - docker

language: python

python: 3.7


before_install:
  - ./bin/install.sh

install:
  - pip install -U wheel setuptools
  - pip install tox-travis
  - pip install codecov

script: tox

after_success: codecov