# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:53
from __future__ import unicode_literals

from django.db import migrations



def forwards_func(apps, schema_editor):
    Sandbox = apps.get_model("sandbox", "Sandbox")
    db_alias = schema_editor.connection.alias
    Sandbox.objects.using(db_alias).bulk_create([
        Sandbox(name="php-sandbox", url="http://pl-sandbox-test.u-pem.fr/sandbox/?action=execute"),
        Sandbox(name="local", url="http://127.0.0.1:8000/sandbox/?action=execute"),
    ])

def reverse_func(apps, schema_editor):
    Sandbox = apps.get_model("sandbox", "Sandbox")
    db_alias = schema_editor.connection.alias
    Sandbox.objects.using(db_alias).filter(name="php-sandbox").delete()
    Sandbox.objects.using(db_alias).filter(name="local").delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
